# Generated by Django 5.2.7 on 2025-10-22 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_order_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='confirmed',
        ),
    ]
