# Generated by Django 5.2.7 on 2025-10-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_order_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirm_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=20),
        ),
    ]
