# Generated by Django 5.2.7 on 2025-10-31 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_order_email_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email_sent',
        ),
    ]
